[project]
name = "MoeMoeBots"
revision = "1.0"

[profiles.default]
OTEL_EXPORTER_OTLP_ENDPOINT = { description = "OTEL_EXPORTER_OTLP_ENDPOINT variable", required = false, default = "http://localhost:4318" }
OTEL_EXPORTER_OTLP_INSECURE = { description = "OTEL_EXPORTER_OTLP_INSECURE variable", required = false, default = "true" }
OTEL_LOGS_EXPORTER = { description = "OTEL_LOGS_EXPORTER variable", required = false, default = "otlp" }
OTEL_NODE_RESOURCE_DETECTORS = { description = "OTEL_NODE_RESOURCE_DETECTORS variable", required = false, default = "all" }
OTEL_SERVICE_NAME = { description = "OTEL_SERVICE_NAME variable", required = false, default = "moemoebots" }
OTEL_TRACES_EXPORTER = { description = "OTEL_TRACES_EXPORTER variable", required = false, default = "otlp" }

MOEGIRL_ZH_BOTUSERNAME = { description = "MOEGIRL_ZH_BOTUSERNAME variable", required = true }
MOEGIRL_ZH_BOTPASSWORD = { description = "MOEGIRL_ZH_BOTPASSWORD secret", required = true }

MOEGIRL_CM_BOTPASSWORD = { description = "MOEGIRL_CM_BOTPASSWORD secret", required = true }
MOEGIRL_CM_BOTUSERNAME = { description = "MOEGIRL_CM_BOTUSERNAME variable", required = true }

MOEGIRL_EN_BOTPASSWORD = { description = "MOEGIRL_EN_BOTPASSWORD secret", required = true }
MOEGIRL_EN_BOTUSERNAME = { description = "MOEGIRL_EN_BOTUSERNAME variable", required = true }

MOEGIRL_JA_BOTUSERNAME = { description = "MOEGIRL_JA_BOTUSERNAME variable", required = true }
MOEGIRL_JA_BOTPASSWORD = { description = "MOEGIRL_JA_BOTPASSWORD secret", required = true }

MOEGIRL_LIBRARY_BOTUSERNAME = { description = "MOEGIRL_LIBRARY_BOTUSERNAME variable", required = true }
MOEGIRL_LIBRARY_BOTPASSWORD = { description = "MOEGIRL_LIBRARY_BOTPASSWORD secret", required = true }

MOEGIRL_UK_BOTPASSWORD = { description = "MOEGIRL_UK_BOTPASSWORD secret", required = true }
MOEGIRL_UK_BOTUSERNAME = { description = "MOEGIRL_UK_BOTUSERNAME variable", required = true }

MOEGIRL_ICU_BOTPASSWORD = { description = "MOEGIRL_ICU_BOTPASSWORD secret", required = true }
MOEGIRL_ICU_BOTUSERNAME = { description = "MOEGIRL_ICU_BOTUSERNAME variable", required = true }

PRTS_BOTUSERNAME = { description = "PRTS_BOTUSERNAME variable", required = true }
PRTS_BOTPASSWORD = { description = "PRTS_BOTPASSWORD secret", required = true }

BWIKI_SESSDATA = { description = "BWIKI_SESSDATA secret", required = true }

[scopes.otel]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
]

[scopes.moegirl_zh]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_ZH_BOTUSERNAME",
	"MOEGIRL_ZH_BOTPASSWORD",
]

[scopes.moegirl_cm]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_CM_BOTUSERNAME",
	"MOEGIRL_CM_BOTPASSWORD",
]

[scopes.moegirl_en]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_EN_BOTUSERNAME",
	"MOEGIRL_EN_BOTPASSWORD",
]

[scopes.moegirl_ja]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_JA_BOTUSERNAME",
	"MOEGIRL_JA_BOTPASSWORD",
]

[scopes.moegirl_library]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_LIBRARY_BOTUSERNAME",
	"MOEGIRL_LIBRARY_BOTPASSWORD",
]

[scopes.moegirl_uk]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_UK_BOTUSERNAME",
	"MOEGIRL_UK_BOTPASSWORD",
]

[scopes.moegirl_icu]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"MOEGIRL_ICU_BOTUSERNAME",
	"MOEGIRL_ICU_BOTPASSWORD",
]

[scopes.prts]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"PRTS_BOTUSERNAME",
	"PRTS_BOTPASSWORD",
]

[scopes.bwiki]
secrets = [
	"OTEL_EXPORTER_OTLP_ENDPOINT",
	"OTEL_EXPORTER_OTLP_INSECURE",
	"OTEL_LOGS_EXPORTER",
	"OTEL_NODE_RESOURCE_DETECTORS",
	"OTEL_SERVICE_NAME",
	"OTEL_TRACES_EXPORTER",
	"BWIKI_SESSDATA",
]
